### ISSUE TITLE
Need some help with .tox file

### ISSUE THREAD

**Issue by 123Remo** [wuestenarchitekten/Twitcher#1]
Hi! Iam very interested to get this working but the .tox file is binary? when i open it with text editor. Ive installed tox for my linux machine but when i try to run Twitcher.tox i get error below. I try run this on raspberry pi with latest rasbian os.

ERROR: No pyproject.toml or setup.py file found. The expected locations are:
  /home/pi/Twitcher-master/pyproject.toml or /home/pi/Twitcher-master/setup.py

Cheers!

**Comment by wuestenarchitekten** [comment]
Hi @123Remo ,

the component is made for the software TouchDesigner (https://derivative.ca), an application only available for Windows or MacOS. 

Cheers
Markus

**Comment by 123Remo** [comment]
Ah ok so this not for python at all then. Ill continue searching another options. Thanks for quick reply!
